database_path: 'utils/'
database_name: 'database.db'
splunk_dir: '/tmp/'
templatemail: 'utils/template/mail.html'
telegram: False
chat_id: 'Chat ID'
token: 'Token'
mail: 'temp@gmail.com'
sendermail: 'temp@temp.com'
smtpmail: 'smtp.mail.com'
portmail: 587
passwdmail: 'passwd'
debug: False
score: 5.0

products:
    - name:
        id: 'magento'
